gripbot:
  # Publish all joint states -----------------------------------
  joint_state_ctrl:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_column_ctrl:
    type: effort_controllers/JointPositionController
    joint: base_column_link
    pid: {p: 10.0, i: 0.01, d: 10.0}
  girdle_visual_ctrl:
    type: effort_controllers/JointPositionController
    joint: girdle_visual_link
    pid: {p: 10.0, i: 0.01, d: 10.0}
  forearm_visual_ctrl:
    type: effort_controllers/JointPositionController
    joint: forearm_visual_link
    pid: {p: 10.0, i: 0.01, d: 10.0}
  arm_visual_ctrl:
    type: effort_controllers/JointPositionController
    joint: arm_visual_link
    pid: {p: 10.0, i: 0.01, d: 10.0}